version: "2"
services:
  mariadb:
    container_name: emails_mariadb
    image: mariadb:10.3
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: administrator
      MYSQL_DATABASE: mygear
      MYSQL_USER: admin
      MYSQL_PASSWORD: administrator
    expose:
      - 3306
